### PR TITLE
Cleanup and log to stdout

### PR DESCRIPTION
**Pull request by ixai**
Reduce the responsibilities of `relayer`.

- Log to `STDOUT`. _ad hoc_ logging facilities are not standard. If anything, it should've been implemented as a `logging` Handler, but that's outside the scope of this PR.
- Because of the above, context handlers are no longer needed. Removed them.
- The Flask Logging Middleware is better off as a standalone middleware (in our case, we replaced it with a WSGI middleware)

### CODE REVIEW

**Comment by CesarLanderos** [comment]
😱 !!, breaking change right (services using relayer need to update their code to fit the new API)?

**Comment by ixai** [comment]
No, the API is intact. Calls to `.log` will not send data to Kafka though. They will output a warning and log to STDOUT. I'll update the reference to some of our services to test this out more thoroughly.

**Comment by CesarLanderos** [comment]
uff <3

**Comment by pablasso** [comment]
Besides, the all the other projects link to an specific `relayer` version, so no worries about this breaking anything before manually making the change  ❤️

**Pull request merged**
